/* Source unique des ateliers de la piste Studio. */
export const studioLessons = [
  { slug: '01-open-a-project', label: 'Open a project', group: 'Open a workspace', command: 'Overview',
    title: 'Open a project and read the overview',
    description: 'Point Studio at a project folder and recognize what it loaded: jobs, workflows, recent runs.' },
  { slug: '02-check-the-api', label: 'Check the API', group: 'Open a workspace', command: 'API online',
    title: 'Confirm Studio is talking to the engine',
    description: 'Read the connection indicator and know what stops working when it goes silent.' },
  { slug: '03-read-the-canvas', label: 'Read the canvas', group: 'Read the canvas', command: 'Jobs configuration',
    title: 'Recognize nodes, ports and edges',
    description: 'Learn what a node, a port and an edge stand for before moving any of them.' },
  { slug: '04-use-the-palette', label: 'Use the palette', group: 'Read the canvas', command: 'Node palette',
    title: 'Find what you need in the node palette',
    description: 'Browse sources, transformations and destinations, and read what each count tells you.' },
  { slug: '05-add-a-source', label: 'Add a source', group: 'Build a job visually', command: 'Sources',
    title: 'Drop your first source on the canvas',
    description: 'Place a CSV source, name it and connect it to the rest of the job.' },
  { slug: '06-configure-a-node', label: 'Configure a node', group: 'Build a job visually', command: 'Inspector',
    title: 'Fill a node without writing YAML',
    description: 'Use the inspector fields and understand which manifest key each one writes.' },
  { slug: '07-see-the-yaml', label: 'See the YAML', group: 'Validate the design', command: 'Hydra DSL',
    title: 'Read the manifests Studio generates',
    description: 'Open the generated DSL and confirm the canvas and the YAML say the same thing.' },
  { slug: '08-reach-valid', label: 'Reach Valid', group: 'Validate the design', command: 'Valid',
    title: 'Resolve what the validity badge reports',
    description: 'Complete an incomplete design until the header turns valid, before any data moves.' },
  { slug: '09-run-the-job', label: 'Run the job', group: 'Run and watch', command: 'Run Job',
    title: 'Launch from the canvas and follow each node',
    description: 'Start the execution and read the state each node reports while it progresses.' },
  { slug: '10-review-a-run', label: 'Review a run', group: 'Run and watch', command: 'Runs',
    title: 'Find a past execution and its result',
    description: 'Locate a finished run, read what it produced and compare it with the previous one.' },
  { slug: '11-compose-jobs', label: 'Compose jobs', group: 'Build a workflow', command: 'Workflow configuration',
    title: 'Turn your jobs into an ordered workflow',
    description: 'Place jobs on the workflow canvas and declare which one waits for which.' },
  { slug: '12-handle-failure', label: 'Handle failure', group: 'Build a workflow', command: 'Containers',
    title: 'Wrap a step in retry and error scopes',
    description: 'Decide what happens when one step fails, without changing the jobs themselves.' }
];
export default studioLessons;

